/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as apponboardingRouteRouteImport } from './routes/(app)/(onboarding)/route'
import { Route as appdashboardRouteRouteImport } from './routes/(app)/(dashboard)/route'
import { Route as apponboardingOnboardingRouteImport } from './routes/(app)/(onboarding)/onboarding'
import { Route as appdashboardDashboardRouteImport } from './routes/(app)/(dashboard)/dashboard'
import { Route as appdashboardCategoriesIndexRouteImport } from './routes/(app)/(dashboard)/categories/index'
import { Route as appdashboardCategoriesGroupIdRouteImport } from './routes/(app)/(dashboard)/categories/$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const apponboardingRouteRoute = apponboardingRouteRouteImport.update({
  id: '/(app)/(onboarding)',
  getParentRoute: () => rootRouteImport,
} as any)
const appdashboardRouteRoute = appdashboardRouteRouteImport.update({
  id: '/(app)/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const apponboardingOnboardingRoute = apponboardingOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => apponboardingRouteRoute,
} as any)
const appdashboardDashboardRoute = appdashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appdashboardRouteRoute,
} as any)
const appdashboardCategoriesIndexRoute =
  appdashboardCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => appdashboardRouteRoute,
  } as any)
const appdashboardCategoriesGroupIdRoute =
  appdashboardCategoriesGroupIdRouteImport.update({
    id: '/categories/$groupId',
    path: '/categories/$groupId',
    getParentRoute: () => appdashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/dashboard': typeof appdashboardDashboardRoute
  '/onboarding': typeof apponboardingOnboardingRoute
  '/categories/$groupId': typeof appdashboardCategoriesGroupIdRoute
  '/categories/': typeof appdashboardCategoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof authSignInRoute
  '/dashboard': typeof appdashboardDashboardRoute
  '/onboarding': typeof apponboardingOnboardingRoute
  '/categories/$groupId': typeof appdashboardCategoriesGroupIdRoute
  '/categories': typeof appdashboardCategoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/(dashboard)': typeof appdashboardRouteRouteWithChildren
  '/(app)/(onboarding)': typeof apponboardingRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(app)/(dashboard)/dashboard': typeof appdashboardDashboardRoute
  '/(app)/(onboarding)/onboarding': typeof apponboardingOnboardingRoute
  '/(app)/(dashboard)/categories/$groupId': typeof appdashboardCategoriesGroupIdRoute
  '/(app)/(dashboard)/categories/': typeof appdashboardCategoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/dashboard'
    | '/onboarding'
    | '/categories/$groupId'
    | '/categories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/dashboard'
    | '/onboarding'
    | '/categories/$groupId'
    | '/categories'
  id:
    | '__root__'
    | '/'
    | '/(app)/(dashboard)'
    | '/(app)/(onboarding)'
    | '/(auth)/sign-in'
    | '/(app)/(dashboard)/dashboard'
    | '/(app)/(onboarding)/onboarding'
    | '/(app)/(dashboard)/categories/$groupId'
    | '/(app)/(dashboard)/categories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appdashboardRouteRoute: typeof appdashboardRouteRouteWithChildren
  apponboardingRouteRoute: typeof apponboardingRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(onboarding)': {
      id: '/(app)/(onboarding)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof apponboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(dashboard)': {
      id: '/(app)/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appdashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/(onboarding)/onboarding': {
      id: '/(app)/(onboarding)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof apponboardingOnboardingRouteImport
      parentRoute: typeof apponboardingRouteRoute
    }
    '/(app)/(dashboard)/dashboard': {
      id: '/(app)/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appdashboardDashboardRouteImport
      parentRoute: typeof appdashboardRouteRoute
    }
    '/(app)/(dashboard)/categories/': {
      id: '/(app)/(dashboard)/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof appdashboardCategoriesIndexRouteImport
      parentRoute: typeof appdashboardRouteRoute
    }
    '/(app)/(dashboard)/categories/$groupId': {
      id: '/(app)/(dashboard)/categories/$groupId'
      path: '/categories/$groupId'
      fullPath: '/categories/$groupId'
      preLoaderRoute: typeof appdashboardCategoriesGroupIdRouteImport
      parentRoute: typeof appdashboardRouteRoute
    }
  }
}

interface appdashboardRouteRouteChildren {
  appdashboardDashboardRoute: typeof appdashboardDashboardRoute
  appdashboardCategoriesGroupIdRoute: typeof appdashboardCategoriesGroupIdRoute
  appdashboardCategoriesIndexRoute: typeof appdashboardCategoriesIndexRoute
}

const appdashboardRouteRouteChildren: appdashboardRouteRouteChildren = {
  appdashboardDashboardRoute: appdashboardDashboardRoute,
  appdashboardCategoriesGroupIdRoute: appdashboardCategoriesGroupIdRoute,
  appdashboardCategoriesIndexRoute: appdashboardCategoriesIndexRoute,
}

const appdashboardRouteRouteWithChildren =
  appdashboardRouteRoute._addFileChildren(appdashboardRouteRouteChildren)

interface apponboardingRouteRouteChildren {
  apponboardingOnboardingRoute: typeof apponboardingOnboardingRoute
}

const apponboardingRouteRouteChildren: apponboardingRouteRouteChildren = {
  apponboardingOnboardingRoute: apponboardingOnboardingRoute,
}

const apponboardingRouteRouteWithChildren =
  apponboardingRouteRoute._addFileChildren(apponboardingRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appdashboardRouteRoute: appdashboardRouteRouteWithChildren,
  apponboardingRouteRoute: apponboardingRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
